name: Terraform Pipeline
on:
  pull_request:
 
permissions:
  id-token: write
  contents: read  
  pull-requests: write

jobs:
  static-test:
    name: static-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125310849:role/Admin
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -backend-config="bucket=demo-bucket-batak-420"

      - name: Terraform validate
        run: terraform validate

      - name: Run tfsec (Static security scan)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: .

      - name: Create or select workspace
        run: terraform workspace new pr-${{github.event.number}} || terraform workspace select pr-${{github.event.number}}

      - name: Cleanup workspace on failure
        if: failure()
        run: |
          terraform workspace select default
          terraform workspace delete pr-${{github.event.number}} || true
        
  dynamic-test:
    name: Apply, Test, Destroy
    runs-on: ubuntu-latest
    needs: static-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125310849:role/Admin
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Terraform init
        run: terraform init -backend-config="bucket=demo-bucket-batak-420"

      - name: Select workspace
        run: terraform workspace select pr-${{github.event.number}}

      - name: Get Runner IP
        id: get_ip
        run: echo "RUNNER_IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV

      - name: Apply temporary infrastructure
        run: terraform apply -auto-approve -var="my_ip=${{ env.RUNNER_IP }}/32"
        timeout-minutes: 30

      - name: Run infrastructure test (using Terratest)
        env:
          TF_WORKSPACE: pr-${{github.event.number}}
        run: |
          cd test
          go mod tidy
          go test -v -timeout 10m

      - name: Destroy temporary infrastructure
        if: always()
        run: |
          echo "Destroying Terraform infrastructure"
          terraform destroy -auto-approve -var="my_ip=${{ env.RUNNER_IP }}/32"
          echo "Deleting Terraform workspace"
          terraform workspace select default
          terraform workspace delete pr-${{github.event.number}}